### ISSUE TITLE
Phylogenetic diversity calculations.ipynb is out of date

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio-cookbook#50]
[This line](https://github.com/biocore/scikit-bio-cookbook/blob/master/Phylogenetic%20diversity%20calculations.ipynb#L57) makes reference to porting BIOM to scikit-bio, but that's [no longer the plan](https://github.com/biocore/scikit-bio/issues/489#issuecomment-74158656).

**Comment by jairideout** [comment]
This notebook is now just a placeholder pointing to UniFrac/PD implementations in scikit-bio and theory in IAB.
