### ISSUE TITLE
Cookbook is in python 2?

### ISSUE THREAD

**Issue by jwdebelius** [biocore/scikit-bio-cookbook#56]
Since scikit-bio is moving to python 3 only with the next release, does this repository also  need to move to Python 3 with that release?

In a related question, should new cookbooks be Python 2 with are Python 3 compatible or just python 3?

**Comment by jairideout** [comment]
> Since scikit-bio is moving to python 3 only with the next release, does this repository also need to move to Python 3 with that release?

Yep!

> In a related question, should new cookbooks be Python 2 with are Python 3 compatible or just python 3?

Since the next release will be Python 3 only, new cookbooks should be written in Python 3 (don't worry about Python 2 compatibility).

**Comment by jairideout** [comment]
Closing as the cookbook is now Python 3.
