### ISSUE TITLE
Broken Link in Alignments and phylogenetic reconstruction.ipynb

### ISSUE THREAD

**Issue by gblanchard4** [biocore/scikit-bio-cookbook#57]
In the [Alignments and phylogenetic reconstruction.ipynb](https://github.com/biocore/scikit-bio-cookbook/blob/ce87303feb538396fc2b25aeb0a9d980dcfdfd60/Alignments%20and%20phylogenetic%20reconstruction.ipynb), there is a linkout to the *scikit-bio Alignment object*. The link currently points to [`http://scikit-bio.org/docs/latest/generated/skbio.alignment.Alignment.html`](http://scikit-bio.org/docs/latest/generated/skbio.alignment.Alignment.html) , which seems to be dead. I was able to get to it via [`http://scikit-bio.org/docs/0.2.0/generated/skbio.alignment.Alignment.html`](http://scikit-bio.org/docs/0.2.0/generated/skbio.alignment.Alignment.html)

**Comment by ebolyen** [comment]
Thanks @gblanchard4, the scikit-bio-cookbook is currently out of date, so the links and code all rely on earlier versions. What probably would make sense moving forward, is to set the cookbook links to match the current version (I think 0.2.3 would work here).

**Comment by gblanchard4** [comment]
Thanks @ebolyen for filling me in! Do you think it could be beneficial to state that on the cookbook main page?

**Comment by ebolyen** [comment]
Ideally we would update the cookbook, but since we are very strapped for time right now, that sounds like a good idea! Would you be open to creating a PR? It looks like we are on scikit-bio 0.4.0 for the cookbook at the moment.

**Comment by jairideout** [comment]
Thanks for reporting this @gblanchard4! We're tentatively releasing scikit-bio 0.5.0 (the first Python 3-only release) on 5/31 and will update the cookbook then to match the latest release.

**Comment by jairideout** [comment]
@gblanchard4, the frontpage now includes the scikit-bio version (currently 0.5.0) in the install instructions. All scikit-bio API links now point to the relevant version (currently 0.5.0) to prevent broken links in the future. Thanks again for reporting the issue!

Note that scikit-bio 0.5.0 isn't released yet so the links are currently dead and there isn't a pip/conda release available. We'll have the release published later today.

**Comment by jairideout** [comment]
scikit-bio 0.5.0 release is live so the new install instructions on the frontpage should work, as well as the 0.5.0 API links in the notebooks. Let us know if you have any issues!

**Comment by gblanchard4** [comment]
Thanks @jairideout and @ebolyen! You guys (and everyone contributing to the scikit-bio project) are doing great work! I've been AFK for a while, but keep it up!

**Comment by jairideout** [comment]
Thanks @gblanchard4!!
